In [3]:
import numpy as np
my_array= np.array([1,2,3]) #1D Array one raw and 3 columns
my_array

array([1, 2, 3])

In [13]:
import numpy as np
my_array = np.array([(1,2,3),(4,5,6)]) #2D array 2 rows and 3 columns
my_array 


array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
import numpy as np
my_2array = np.array ((([1,2,3],[3,5,6]),([7,8,9],[9,10,11])))
my_2array #3D array 2layers,2 rows , 3 columns
my_2array.shape

(2, 2, 3)

In [15]:
import numpy as np
zero_array= np.zeros([1,2]) #1D array with 2 coumns [] indecade the num of columns in the 1 d array
zero1_array= np.zeros((1,2)) 
print(zero_array)
print(zero1_array)
random_array=np.random.random((5,5))
print(random_array)
random_int= np.random.randint (1,10,(3,3)) # int values from 1 to 10 3*3 matrix
print(random_int)
print(random_int.dtype)
# when using the functions .zeros,.ones,.random.rand what we type in the parentheses is the shape of the array
# when typing a manual array what we type is the array elements


[[0. 0.]]
[[0. 0.]]
[[0.7029344  0.15369292 0.28993958 0.3921089  0.44875944]
 [0.48260629 0.61166329 0.3320974  0.11072309 0.64226407]
 [0.16200909 0.67537943 0.90363079 0.07520293 0.91942651]
 [0.92814325 0.75551172 0.44186389 0.02035944 0.32098288]
 [0.07351695 0.44792108 0.92649437 0.7527253  0.30609936]]
[[9 5 9]
 [3 4 1]
 [4 4 1]]
int32


In [1]:
import numpy as np 
myarray= np.random.random((5,4))
print(myarray)
print(myarray.shape)
print(type(myarray))
print(myarray.min())
print(myarray.max())
print(np.mean(myarray))
print(np.sum(myarray))

[[0.878456   0.69726931 0.4132435  0.89629656]
 [0.65172903 0.3493064  0.06262906 0.48192642]
 [0.08615697 0.87760612 0.12164854 0.16605413]
 [0.62664792 0.05947395 0.5012812  0.90765252]
 [0.2913181  0.11008167 0.37385461 0.87645296]]
(5, 4)
<class 'numpy.ndarray'>
0.05947395013160006
0.9076525174529378
0.4714542488945013
9.429084977890026


In [2]:
import numpy as np
range_array=np.arange(10) #10 items from 0 to 9
print(range_array)
range2_array = np.arange (0,13) #12 items starting with zero to 12
print(range2_array)
range3_array = np.arange(0,13,3) # 3 spaces betweem each item
print(range3_array)
linespace_array = np.linspace (0,3,5) # i want 5 items between 0 ansd 3
print(linespace_array)


[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
[ 0  3  6  9 12]
[0.   0.75 1.5  2.25 3.  ]


In [7]:
### array slicing ###
array=np.array((1,2,3,4,7))
print(array[0])
print(array[-1])
print(array[1:4]) #items 1,2,3
#2d array
array1= np.array([[1,2,3],[4,5,6],[7,8,9]]) 
print(array1)
print(array1[0,2])

1
7
[2 3 4]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3


In [8]:
matrix=np.array(([5,10,20],[20,25,30],[35,40,10]))
print(matrix)
print(matrix[1]) # second row
print(matrix[0])# first row
print(matrix[1][1]) # second row, second element
print(matrix[1,1]) 
print(matrix[:2,1:]) # reacing the first 2 rows and the second 2 columns
print(matrix[:1,1:]) # reaching the first row and the second 2 columns
print(matrix[2,:]) # reaching all the elements in the 3rd row
print(matrix[0,1::2]) # reaching the first row , second 2 columns with 2 stepsize

[[ 5 10 20]
 [20 25 30]
 [35 40 10]]
[20 25 30]
[ 5 10 20]
25
25
[[10 20]
 [25 30]]
[[10 20]]
[35 40 10]
[10]


In [9]:
a=np.arange(0,12)
bool_a= a>4
print(a)
print(bool_a) #the boolen array of a>4
print(a[bool_a]) # the actual array of the boolen array
print(a[a>1]) # the actual array of the boolen a>1

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[False False False False False  True  True  True  True  True  True  True]
[ 5  6  7  8  9 10 11]
[ 2  3  4  5  6  7  8  9 10 11]


In [10]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([7,8,9,10,11])
print(arr1+arr2) # adding arrays values
print(np.add(arr1,arr2))
print(arr1-arr2) # substracting 
print(np.subtract(arr1,arr2))
print(arr1*arr2) #multiplying array vlue
print(np.multiply(arr1,arr2))
print(arr2+12) # add 12 to each element in array2 
print(arr1*3) # multiply each element in array 1 by 3 
print(arr1*3.3) # we can multiply arrays by float but cant multiply sequence by float
b=[1,2,3,4,5] 
print(b*3.3)

[ 8 10 12 14 16]
[ 8 10 12 14 16]
[-6 -6 -6 -6 -6]
[-6 -6 -6 -6 -6]
[ 7 16 27 40 55]
[ 7 16 27 40 55]
[19 20 21 22 23]
[ 3  6  9 12 15]
[ 3.3  6.6  9.9 13.2 16.5]


TypeError: can't multiply sequence by non-int of type 'float'

In [ ]:
x= np.array([[1,4,5],[10,11,12],[20,30,40]])
v=np.array([1,2,1])
y=np.empty_like(x) # creating a new empty matrix with the same shape of x 
#ADDING V TO EACH ROW OF X
for i in range(3): # in range (num of rows)
    y[i,:]= x[i, :]+v # i REPRESENTS THE ROW AND : REPRESENTS ALL THE COLUMNS
print (y)


[[ 2  6  6]
 [11 13 13]
 [21 32 41]]


In [11]:
#dot product of two 1d arrays
a= np.array([1,2,3])
b= np.array([7,8,9])
result= np.dot(a,b) # 1*7+2*8+3+9
print(result)
#dot product of two 2d arrays
A= np.array(([5,6,7],[9,8,3]))
B=np.array(([1,4,6],[5,4,7])) 
Result=np.dot(A,B) # dot product in 2d arrays only works when the num of columns in the first matrix matches the num of rows in the second matrix
print(Result)

50


ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [ ]:
#dot product of two 2d arrays
A= np.array(([5,6],[9,8]))
B=np.array(([1,4,6],[5,4,7]))
Result=np.dot(A,B)
print(Result)
C=np.array(([5,6],[9,8]))
D= np.array(([1,4],[5,7]))
Result1= np.dot(C,D)
print(Result1)
Result2=C*D # Matrix multiplications
print(Result2)

[[ 35  44  72]
 [ 49  68 110]]
[[35 62]
 [49 92]]
[[ 5 24]
 [45 56]]


In [ ]:
#Task1 Slicing
AB= np.array(([1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]))
print(AB)
print(AB[2:4,0:2])
print(AB[0,1],AB[1,2],AB[2,3],AB[3,4]) #accessing individual elements
ABC= np.zeros_like(AB)
ABC[0,1]=AB[0,1]
ABC[1,2]=AB[1,2]
ABC[2,3]=AB[2,3]
ABC[3,4]=AB[3,4]
print(ABC) 
ABD= np.zeros_like(AB)
ABD[0,3:5] = AB[0,3:5]
ABD[4:6,3:5]=AB[4:6,3:5]
print(ABD)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]
[[11 12]
 [16 17]]
2 8 14 20
[[ 0  2  0  0  0]
 [ 0  0  8  0  0]
 [ 0  0  0 14  0]
 [ 0  0  0  0 20]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]]
[[ 0  0  0  4  5]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [ 0  0  0 24 25]
 [ 0  0  0 29 30]]


In [ ]:
#Special matrices shapes 
S_matrix=np.array(([1,2,3],[4,5,6],[7,8,9])) #Square matrix
print(S_matrix)
# diagonal \ matrix
D_matrix=np.diag([1,2,3])
print(D_matrix)
# identity matrix
I_matrix=np.eye(3) #The np.eye(3) function creates a 3x3 identity matrix. Identity matrices are used as the multiplicative identity in matrix algebra.
print(I_matrix)
#Upper traingle 
U_matrix=np.array(([1,2,3],[0,1,5],[0,0,7])) # THE TRIANGLE BASE IN THE UPPER ROWS
print(U_matrix)
L_matrix=np.array(([0,0,2],[0,1,2],[2,2,3]))
print(L_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 2 3]
 [0 1 5]
 [0 0 7]]
[[0 0 2]
 [0 1 2]
 [2 2 3]]


In [ ]:
# TRANSPOSE
Matrixx=np.array(([1,2,3],[4,5,6],[7,8,9]))
Result3=np.transpose(Matrixx) # switches rows and columns
print(Result3)
#Symmetric matrix remains the same after transposing


[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#Special calculations
M=np.array(([1,2,3],[4,5,6],[7,8,9]))
trace=np.trace(M)
print('Trace of the matrix:',trace) # The np.trace() function calculates the trace of a matrix, which is often used in machine learning algorithms and various mathematical computations.
F=np.array(([4,6],[3,8]))
determinant= np.linalg.det(F) #A scalar value that is a function of a square matrix, often used in solving linear equations, calculating matrix inverses, and more
print(determinant)
inverse=np.linalg.inv(F) #A matrix that, when multiplied with the original matrix, yields the identity matrix.
print(inverse)
rank=np.linalg.matrix_rank(M) #The rank of a matrix is the maximum number of linearly independent column vectors in the matrix.
print(rank)

Trace of the matrix: 15
14.000000000000004
[[ 0.57142857 -0.42857143]
 [-0.21428571  0.28571429]]
2


In [12]:
#Task2
D1= np.arange(0,10)
print(D1)
Ident=np.eye(3)
print(Ident)
odd=D1[D1 %2 !=0]
print(odd) 
odd1=[]
for number in D1:
    if number %2 !=0:
        odd1.append(number)

print(odd1)
D2= np.arange(1,13)
print(D2)
D3=D2.reshape(3,4) # to reshape a 1d array into a 2d array the size must match
# THE SIZE OF D2 IS 12 AND THE SIZA OF D3 IS 12=3*4
print(D3)
D4=np.random.random((5,5))
print(D4)
Normalized= (D4-D4.min())/(D4.max()-D4.min()) # normalization formula
print(Normalized)
D5=np.array(([1,2,3],[4,5,6],[7,8,9],[2,5,8],[1,4,7])) #np.random.random((5,3))
D6=np.array(([1,2],[3,4],[5,6]))
result4=np.dot(D5,D6)
print(result4)
D7=np.arange(11)
print(D7)
D7[(D7 >= 3) & (D7 <= 8)] *= -1
#D7[3:9]*=-1
print(D7)


[0 1 2 3 4 5 6 7 8 9]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[np.int64(1), np.int64(3), np.int64(5), np.int64(7), np.int64(9)]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0.98692964 0.86345162 0.47704001 0.35492795 0.80416919]
 [0.00553144 0.35411442 0.99516552 0.55192913 0.31000955]
 [0.23922433 0.08798839 0.62354402 0.11527098 0.34031592]
 [0.59966423 0.15372801 0.62990668 0.22112501 0.78361042]
 [0.50041287 0.20370298 0.82441524 0.06714644 0.09806743]]
[[0.99167785 0.86690646 0.47644739 0.35305626 0.80700308]
 [0.         0.35223422 1.         0.55212093 0.30766737]
 [0.23614071 0.08332064 0.62448596 0.11088901 0.33829118]
 [0.60035604 0.14974886 0.63091526 0.21785181 0.78622897]
 [0.50006506 0.20024729 0.8274612  0.06226039 0.09350526]]
[[ 22  28]
 [ 49  64]
 [ 76 100]
 [ 57  72]
 [ 48  60]]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10]
