## Introduction 👋

### What is NumPy?
[![NumPy](https://img.shields.io/badge/Numpy-777BB4?style=flat&logo=numpy&logoColor=white)](https://numpy.org/) stands for numeric python which is a python package for the computation and processing of the multidimensional and single dimensional array elements.

**Travis Oliphant** created NumPy package in 2005 by injecting the features of the ancestor module Numeric into another module Numarray.

It is an extension module of Python which is mostly written in "C". It provides various functions which are capable of performing the numeric computations with a high speed.

NumPy provides various powerful data structures, implementing multi-dimensional arrays and matrices. These data structures are used for the optimal computations regarding arrays and matrices.

In this tutorial, we will go through the numeric python library NumPy.

### The need of NumPy?
With the revolution of data science, data analysis libraries like NumPy, SciPy, Pandas, etc. have seen a lot of growth. With a much easier syntax than other programming languages, python is the first choice language for the data scientist.

NumPy provides a convenient and efficient way to handle the vast amount of data. NumPy is also very convenient with Matrix multiplication and data reshaping. NumPy is fast which makes it reasonable to work with a large set of data.

There are the following advantages of using NumPy for data analysis.

* NumPy performs array-oriented computing.
* It efficiently implements the multidimensional arrays.
* It performs scientific computations.
* It is capable of performing Fourier Transform and reshaping the data stored in multidimensional arrays.
* NumPy provides the in-built functions for linear algebra and random number generation.

Nowadays, NumPy in combination with SciPy and Mat-plotlib is used as the replacement to MATLAB as Pyt-

## Table of contents 📋

# Python NumPy

In this class, you will learn various NumPy concepts like how to install NumPy, arrays, functions, matrix multiplication, etc. This NumPy in Python tutorial will help you learn all Python NumPy basics.

**[Numpy](http://www.numpy.org/)** (‘Numerical Python’) is the core open source library for scientific computing in Python. It is a Linear Algebra Library for Python, it is so important for Finance with Python. It is a very useful library to perform mathematical and statistical operations in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. In this part, we will review the essential functions that you need to know for the tutorial on 'TensorFlow.'

## Why use NumPy?

NumPy is memory efficiency, meaning it can handle the vast amount of data more accessible than any other library. Besides, NumPy is very convenient to work with, especially for matrix multiplication and reshaping. On top of that, NumPy is fast. In fact, TensorFlow and Scikit learn to use NumPy array to compute the matrix multiplication in the back end.

## Python NumPy Array: 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.

## How to Install NumPy?

NumPy is installed by default with Anaconda.

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries like numpy) sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
`conda install numpy`

### Import NumPy and Check Version

The command to import numpy is

```python
import numpy as np
```
Above code renames the **`numpy`** namespace to **`np`**.

In [1]:
# To check your installed version of Numpy use the command

print (np.__version__)

1.20.1


In [29]:
import numpy as np 

In [33]:
my_array = np.array([1,2,3])
my_array

array([1, 2, 3])

# NumPy Basics

### NumPy Basics

| Operator | Description |
|:---- |:---- |
| **`np.array([1,2,3])`**           | **1d array** | 
| **`np.array([(1,2,3),(4,5,6)])`** | **2d array** | 
| **`np.arange(start,stop,step)`**  | **range array**  | 

### Placeholders

| Operator | Description |
|:---- |:---- |
| **`np.linspace(0,2,9)`**      | **Add evenly spaced values btw interval to array of length** |
| **`np.zeros((1,2))`**         | **Create and array filled with zeros** |
| **`np.ones((1,2))`**          | **Creates an array filled with ones** |
| **`np.random.random((5,5))`** | **Creates random array** |
| **`np.empty((2,2))`**         | **Creates an empty array** |

### Array

| Operator | Description |
|:---- |:---- |
| **`array.shape`**        | **Dimensions (Rows,Columns)** |
| **`len(array)`**         | **Length of Array** |
| **`array.ndim`**         | **Number of Array Dimensions** |
| **`array.dtype`**        | **Data Type** |
| **`array.astype(type)`** | **Converts to Data Type** |
| **`type(array)`**        | **Type of Array** |

### Copying/Sorting

| Operator | Description |
|:---- |:---- |
| **`np.copy(array)`**       | **Creates copy of array** |
| **`other = array.copy()`** | **Creates deep copy of array** |
| **`array.sort()`**         | **Sorts an array** |
| **`array.sort(axis=0)`**   | **Sorts axis of array** |

## Array Manipulation

### Adding or Removing Elements

| Operator | Description |
|:---- |:---- |
| **`np.append(a,b)`**               | **Append items to array** |
| **`np.insert(array, 1, 2, axis)`** | **Insert items into array at axis 0 or 1** |
| **`np.resize((2,4))`**             | **Resize array to shape(2,4)** |
| **`np.delete(array,1,axis)`**      | **Deletes items from array** |

### Combining Arrays

| Operator | Description |
|:---- |:---- |
| **`np.concatenate((a,b),axis=0)`** | **Split an array into multiple sub-arrays.** |
| **`np.vstack((a,b))`**             | **Split an array in sub-arrays of (nearly) identical size** |
| **`np.hstack((a,b))`**             | **Split the array horizontally at 3rd index** |

### More

| Operator | Description |
|:---- |:---- |
| **`other = ndarray.flatten()`**       | **Flattens a 2d array to 1d** |
| **`array = np.transpose(other)`**     | **Transpose array** |
| **`array.T`**                         | **Transpose array** |
| **`inverse = np.linalg.inv(matrix)`** | **Inverse of a given matrix** |

## Slicing and Subsetting

| Operator | Description |
|:---- |:---- |
| **`array[i]`**        | **1d array at index i** |
| **`array[i,j]`**      | **2d array at index[i][j]** |
| **`array[i<4]`**      | **Boolean Indexing, see Tricks** |
| **`array[0:3]`**      | **Select items of index 0, 1 and 2** |
| **`array[0:2,1]`**    | **Select items of rows 0 and 1 at column 1** |
| **`array[:1]`**       | **Select items of row 0 (equals array[0:1, :])** |
| **`array[1:2, :]`**   | **Select items of row 1** |
| **`[comment]: <> (`** | **array[1,...]** |
| **`array[ : :-1]`**   | **Reverses array** |

## Mathematics

### Operations

| Operator | Description |
|:---- |:---- |
| **`np.add(x,y)`**        | **Addition** |
| **`np.substract(x,y)`**  | **Subtraction** |
| **`np.divide(x,y)`**     | **Division** |
| **`np.multiply(x,y)`**   | **Multiplication** |
| **`np.sqrt(x)`**         | **Square Root** |
| **`np.sin(x)`**          | **Element-wise sine** |
| **`np.cos(x)`**          | **Element-wise cosine** |
| **`np.log(x)`**          | **Element-wise natural log** |
| **`np.dot(x,y)`**        | **Dot product** |
| **`np.roots([1,0,-4])`** | **Roots of a given polynomial coefficients** |

### Comparison

| Operator | Description |
|:----: |:---- |
| **`==`** | **Equal** |
| **`!=`** | **Not equal** |
| **`<`**  | **Smaller than** |
| **`>`**  | **Greater than** |
| **`<=`** | **Smaller than or equal** |
| **`>=`** | **Greater than or equal** |
| **`np.array_equal(x,y)`** | **Array-wise comparison** |

## Basic Statistics

| Operator | Description |
|:---- |:---- |
| **`np.mean(array)`**   | **Mean** |
| **`np.median(array)`** | **Median** |
| **`array.corrcoef()`** | **Correlation Coefficient** |
| **`np.std(array)`**    | **Standard Deviation** |

### More

| Operator | Description |
|:---- |:---- |
| **`array.sum()`**          | **Array-wise sum** |
| **`array.min()`**          | **Array-wise minimum value** |
| **`array.max(axis=0)`**    | **Maximum value of specified axis** |
| **`array.cumsum(axis=0)`** | **Cumulative sum of specified axis** |

# Python NumPy Array: 

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.

## NumPy Array Types:

<div>
<img src="img/array.png" width="700"/>
</div>

In [34]:
 import numpy as np 

In [35]:
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [36]:
my_np_array= np.array(my_list)
my_np_array

array([1, 2, 3, 4])

In [38]:
my_list1 = np.array(range(1,11))
my_list1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [47]:
my_list1.ndim

1

In [42]:
print(type(my_list1))

<class 'numpy.ndarray'>


In [40]:
type(my_list)

list

In [50]:
my_list2= np.array([[1,2,3,4],[5,6,7,8]])
my_list2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [45]:
my_list2.shape

(2, 4)

In [46]:
my_list2.ndim

2

In [55]:
my_list2.itemsize

4

In [56]:
my_list2.size

8

## Array datatypes

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. The full list of NumPy datatype (dtypes) can be found in the [NumPy documentation](http://docs.scipy.org/doc/numpy/user/basics.types.html).

<div>
<img src="http://docs.scipy.org/doc/numpy/_images/dtype-hierarchy.png" width="600"/>
</div>

The two biggest things to remember are

- Missing values (NaN) cast integer or boolean arrays to floats
- NumPy arrays only have a single dtype for every element
- the object dtype is the fallback

Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. For example:

In [64]:
a= np.array([1.1,2,3],dtype='int64')

In [65]:
a

array([1, 2, 3], dtype=int64)

In [67]:
np.random.rand(3,5)

array([[0.93309866, 0.2305084 , 0.56695925, 0.8837321 , 0.00527316],
       [0.57282818, 0.03057525, 0.71871178, 0.93429279, 0.04231182],
       [0.85507829, 0.51491327, 0.80009305, 0.09037474, 0.61175065]])

In [73]:
my_arr = np.random.randn(3,5)
my_arr

array([[-2.11322443,  1.40363011, -0.27396492, -0.43116055,  1.08221944],
       [-0.18524823,  0.20816628,  0.22791026, -1.55675864, -0.57763623],
       [-1.84450601, -0.80169359, -0.77772458,  1.69285583, -1.38802023]])

In [74]:
my_arr.min()

-2.11322443381862

In [75]:
my_arr.max()

1.6928558293165543

In [76]:
np.zeros(4)

array([0., 0., 0., 0.])

In [79]:
np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [81]:
np.ones((4,2),dtype= 'float')

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [100]:
np.full((3,2),np.random.randn())

array([[1.572064, 1.572064],
       [1.572064, 1.572064],
       [1.572064, 1.572064]])

In [110]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [111]:
like_arr =np.full_like(arr,np.log(100))
like_arr

array([4, 4, 4, 4])

In [112]:
mul_arr= arr *like_arr
mul_arr

array([ 4,  8, 12, 16])

In [124]:
arr = np.array([[1,2,3,4]])
arr

array([[1, 2, 3, 4]])

In [123]:
np.repeat(arr,2,axis=1)

array([[1, 1, 2, 2, 3, 3, 4, 4]])

In [125]:
np.repeat(arr,2,axis=0)

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [126]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# array indexing

In [142]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [143]:
slice_arr = arr[0:5]
slice_arr

array([1, 2, 3, 4, 5])

In [144]:
slice_arr[:] = 100
slice_arr

array([100, 100, 100, 100, 100])

In [145]:
arr

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [147]:
arr2 = arr.copy()
arr2

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [176]:
arr2d = np.array(([1,2,3,5,6],[6,7,8,54,4],[11,17,81,6,4]))
arr2d

array([[ 1,  2,  3,  5,  6],
       [ 6,  7,  8, 54,  4],
       [11, 17, 81,  6,  4]])

In [184]:
arr2d[0:][:3]

array([[ 1,  2,  3,  5,  6],
       [ 6,  7,  8, 54,  4],
       [11, 17, 81,  6,  4]])

In [185]:
arr2d[1:,:2]

array([[ 6,  7],
       [11, 17]])

In [192]:
arr2d1 = np.array(([1,2,3,5,6]))
arr2d2= np.array(([12,212,1231,25,26]))

sum =arr2d1 + arr2d2
sum

array([  13,  214, 1234,   30,   32])

In [193]:
np.sqrt(sum)

array([ 3.60555128, 14.62873884, 35.12833614,  5.47722558,  5.65685425])

In [195]:
np.min(sum)

13

In [196]:
np.cos(sum)

array([ 0.90744678,  0.93171141, -0.79855062,  0.15425145,  0.83422336])

In [204]:
a = np.ones((2,3))
a 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [209]:
b = np.full((3,2),3)
b

array([[3, 3],
       [3, 3],
       [3, 3]])

In [211]:
a*b

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [210]:
np.matmul(a,b)

array([[9., 9.],
       [9., 9.]])

In [188]:
arr2d*2

array([ 2,  4,  6, 10, 12])

In [189]:
arr2d-2

array([-1,  0,  1,  3,  4])

In [190]:
arr2d*2

array([ 2,  4,  6, 10, 12])

In [222]:
arr= np.array([[12,212,1],[1231,25,26]])
arr

array([[  12,  212,    1],
       [1231,   25,   26]])

In [224]:
arr.flatten(order='F')

array([  12, 1231,  212,   25,    1,   26])

In [225]:
arr.flatten(order='c')

array([  12,  212,    1, 1231,   25,   26])

In [220]:
arr.reshape(3,2,order='F')

array([[  12,   25],
       [1231,    1],
       [ 212,   26]])

In [221]:
arr.reshape(3,2,order='c')

array([[  12,  212],
       [   1, 1231],
       [  25,   26]])

In [ ]:
arr.reshape(3,2,order='c')

In [226]:
arr1= np.array([[12,212,1]])
arr2= np.array([[1231,25,26]])


In [227]:
arr1

array([[ 12, 212,   1]])

In [228]:
arr2

array([[1231,   25,   26]])

In [230]:
np.vstack([arr1,arr2])

array([[  12,  212,    1],
       [1231,   25,   26]])

In [231]:
np.hstack([arr1,arr2])

array([[  12,  212,    1, 1231,   25,   26]])

In [249]:
normal = np.random.normal(5,5,2)
normal

array([ 1.6627072 , 10.99654404])

In [235]:
help(np.random.normal)

Help on built-in function normal:

normal(...) method of numpy.random.mtrand.RandomState instance
    normal(loc=0.0, scale=1.0, size=None)

    Draw random samples from a normal (Gaussian) distribution.

    The probability density function of the normal distribution, first
    derived by De Moivre and 200 years later by both Gauss and Laplace
    independently [2]_, is often called the bell curve because of
    its characteristic shape (see the example below).

    The normal distributions occurs often in nature.  For example, it
    describes the commonly occurring distribution of samples influenced
    by a large number of tiny, random disturbances, each with its own
    unique distribution [2]_.

    .. note::
        New code should use the `~numpy.random.Generator.normal`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.

    Parameters
    ----------
    loc : float or array_like of floats
        Mean ("centre") o